version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ml-service:
    volumes:
      - ./ml_service:/app
    command: ["uvicorn", "service.server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./frontend/src:/app/src
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
